# Generated by Django 4.1.5 on 2023-01-12 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grind_size', models.CharField(max_length=50)),
                ('photoUrl', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=20)),
                ('dose_min', models.PositiveIntegerField()),
                ('dose_max', models.PositiveIntegerField()),
                ('weight_max', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brew_time', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('dose', models.PositiveIntegerField()),
                ('recipe_name', models.CharField(max_length=35)),
                ('water_temp', models.PositiveIntegerField()),
                ('default', models.BooleanField()),
                ('published', models.BooleanField()),
                ('grind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialinginapi.grind')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialinginapi.method')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('fav_roast', models.CharField(max_length=15)),
                ('fav_shop', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('photo_url', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=50)),
                ('brew_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialinginapi.method')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('order', models.PositiveIntegerField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialinginapi.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('setting', models.CharField(max_length=150)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialinginapi.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='MethodEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialinginapi.method')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialinginapi.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialinginapi.user')),
            ],
        ),
    ]
