# Generated by Django 4.1.5 on 2023-01-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialinginapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='recipe',
            new_name='recipe_id',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='grind',
            old_name='photoUrl',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='method',
            old_name='photo_url',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='methodequipment',
            old_name='method',
            new_name='method_id',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='grind',
            new_name='grind_id',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='method',
            new_name='method_id',
        ),
        migrations.RenameField(
            model_name='recipeequipment',
            old_name='recipe',
            new_name='recipe_id',
        ),
        migrations.RenameField(
            model_name='step',
            old_name='recipe',
            new_name='recipe_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='photo_url',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='brew_method',
            new_name='method_id',
        ),
        migrations.AlterField(
            model_name='method',
            name='dose_max',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='dose_min',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='weight_max',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
