# Generated by Django 4.1.5 on 2023-01-22 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialinginapi', '0002_alter_recipe_brew_time_alter_recipe_dose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='brew_time',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='dose',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='published',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='weight',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
