# Generated by Django 4.1.5 on 2023-01-22 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dialinginapi', '0003_alter_recipe_brew_time_alter_recipe_dose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dialinginapi.user'),
        ),
    ]
