# Generated by Django 4.1.5 on 2023-01-12 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialinginapi', '0003_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='water_temp',
        ),
    ]
