# Generated by Django 4.1.5 on 2023-01-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialinginapi', '0004_remove_recipe_water_temp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='default value', max_length=50),
            preserve_default=False,
        ),
    ]
