# Generated by Django 4.1.5 on 2023-01-23 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dialinginapi', '0004_alter_owner_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dialinginapi.recipe'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dialinginapi.user'),
        ),
    ]
