# Generated by Django 4.1.5 on 2023-01-14 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialinginapi', '0005_rename_name_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
